boxing.icons["bobenemies"] = {
	["graphics/icons/alien-artifact-blue.png"] = true,
	["graphics/icons/alien-artifact-green.png"] = true,
	["graphics/icons/alien-artifact-orange.png"] = true,
	["graphics/icons/alien-artifact-purple.png"] = true,
	["graphics/icons/alien-artifact-red.png"] = true,
	["graphics/icons/alien-artifact-yellow.png"] = true,
	["graphics/icons/small-alien-artifact-blue.png"] = true,
	["graphics/icons/small-alien-artifact-green.png"] = true,
	["graphics/icons/small-alien-artifact-orange.png"] = true,
	["graphics/icons/small-alien-artifact-purple.png"] = true,
	["graphics/icons/small-alien-artifact-red.png"] = true,
	["graphics/icons/small-alien-artifact-yellow.png"] = true,
	["graphics/icons/small-alien-artifact.png"] = true,
};
