boxing.mods["boblogistics"] = {
	["graphics/icons/flying-robot-frame-2.png"] = true,
	["graphics/icons/flying-robot-frame-3.png"] = true,
	["graphics/icons/flying-robot-frame-4.png"] = true,
	["graphics/icons/robot-brain-construction-2.png"] = true,
	["graphics/icons/robot-brain-construction-3.png"] = true,
	["graphics/icons/robot-brain-construction-4.png"] = true,
	["graphics/icons/robot-brain-construction.png"] = true,
	["graphics/icons/robot-brain-logistic-2.png"] = true,
	["graphics/icons/robot-brain-logistic-3.png"] = true,
	["graphics/icons/robot-brain-logistic-4.png"] = true,
	["graphics/icons/robot-brain-logistic.png"] = true,
	["graphics/icons/robot-tool-construction.png"] = true,
	["graphics/icons/robot-tool-logistic.png"] = true,
};
